### ISSUE TITLE
Allow handling of connection errors (i.e. ConnectionReset)

### ISSUE THREAD

**Issue by C0Nd3Mnd** [fox-cat/coward#11]
**Is your feature request related to a problem? Please describe.**
Disclaimer: I'm new to using Deno in general and also to using Coward.

Currently I can't seem to find a way to handle connection errors like these:

```
error: Uncaught ConnectionReset: Socket has already been closed
      throw new Deno.errors.ConnectionReset("Socket has already been closed");
            ^
    at WebSocketImpl.enqueue (https://deno.land/std/ws/mod.ts:306:13)
    at WebSocketImpl.send (https://deno.land/std/ws/mod.ts:327:17)
    at https://deno.land/x/coward/src/gateway/WebsocketHandler.ts:40:14
    at fire ($deno$/web/timers.ts:179:3)
    at handleTimerMacrotask ($deno$/web/timers.ts:44:5)
```

_(this usually occurs after sometime of running the client)_

Currently I can't find a way to try-catch the error. As far as I know you can register an error handler to the socket object. The `gateway` property is private:

https://github.com/fox-cat/coward/blob/e6f3e929a1f1a5d93dcd6320183cbfa25fc1179a/src/Client.ts#L25

**Describe the solution you'd like**
I would like to be able to catch/handle the error in some way (i.e. reconnect), either by being able to attach an error handler function somehow or via an option that lets Coward handle connection errors automatically (=> automatically reconnect, don't know if that's a good idea though).

**Describe alternatives you've considered**

**Additional context**

**Comment by fox-cat** [comment]
hey, thanks for the issue request
this seems to happen when the client attempts to heartbeat or identify after the websocket has been closed;
automatic reconnection seems like a good idea as well

**Comment by fox-cat** [comment]
commit ab55db6 fixes (or, attempts to fix) this issue by automatically reconnecting,
im not closing the issue because this hasnt been heavily tested haha

**Comment by C0Nd3Mnd** [comment]
Alright, I'll just let my test bot run with the latest `master` now and see if it crashes or indeed reconnects as it should.

**Comment by C0Nd3Mnd** [comment]
Seems like the issue still occurs after a while:

```
[coward] error: something went wrong when trying to heartbeat:
ConnectionReset: Socket has already been closed
    at WebSocketImpl.enqueue (https://deno.land/std/ws/mod.ts:306:13)
    at WebSocketImpl.send (https://deno.land/std/ws/mod.ts:327:17)
    at Gateway.singleHeartbeat (https://deno.land/x/coward/src/network/gateway/WebsocketHandler.ts:63:13)
    at https://deno.land/x/coward/src/network/gateway/WebsocketHandler.ts:74:11
    at fire ($deno$/web/timers.ts:179:3)
    at handleTimerMacrotask ($deno$/web/timers.ts:44:5)
[coward] error: something went wrong when trying to heartbeat:
ConnectionReset: Socket has already been closed
    at WebSocketImpl.enqueue (https://deno.land/std/ws/mod.ts:306:13)
    at WebSocketImpl.send (https://deno.land/std/ws/mod.ts:327:17)
    at Gateway.singleHeartbeat (https://deno.land/x/coward/src/network/gateway/WebsocketHandler.ts:63:13)
    at https://deno.land/x/coward/src/network/gateway/WebsocketHandler.ts:74:11
    at fire ($deno$/web/timers.ts:179:3)
    at handleTimerMacrotask ($deno$/web/timers.ts:44:5)
[coward] error: something went wrong when trying to heartbeat:
ConnectionReset: Socket has already been closed
    at WebSocketImpl.enqueue (https://deno.land/std/ws/mod.ts:306:13)
    at WebSocketImpl.send (https://deno.land/std/ws/mod.ts:327:17)
    at Gateway.singleHeartbeat (https://deno.land/x/coward/src/network/gateway/WebsocketHandler.ts:63:13)
    at https://deno.land/x/coward/src/network/gateway/WebsocketHandler.ts:74:11
    at fire ($deno$/web/timers.ts:179:3)
    at handleTimerMacrotask ($deno$/web/timers.ts:44:5)
[coward] error: something went wrong when trying to heartbeat:
ConnectionReset: Socket has already been closed
    at WebSocketImpl.enqueue (https://deno.land/std/ws/mod.ts:306:13)
    at WebSocketImpl.send (https://deno.land/std/ws/mod.ts:327:17)
    at Gateway.singleHeartbeat (https://deno.land/x/coward/src/network/gateway/WebsocketHandler.ts:63:13)
    at https://deno.land/x/coward/src/network/gateway/WebsocketHandler.ts:74:11
    at fire ($deno$/web/timers.ts:179:3)
    at handleTimerMacrotask ($deno$/web/timers.ts:44:5)
[coward] error: something went wrong when trying to heartbeat:
ConnectionReset: Socket has already been closed
    at WebSocketImpl.enqueue (https://deno.land/std/ws/mod.ts:306:13)
    at WebSocketImpl.send (https://deno.land/std/ws/mod.ts:327:17)
    at Gateway.singleHeartbeat (https://deno.land/x/coward/src/network/gateway/WebsocketHandler.ts:63:13)
    at https://deno.land/x/coward/src/network/gateway/WebsocketHandler.ts:74:11
    at fire ($deno$/web/timers.ts:179:3)
    at handleTimerMacrotask ($deno$/web/timers.ts:44:5)
[coward] error: something went wrong when trying to heartbeat:
ConnectionReset: Socket has already been closed
    at WebSocketImpl.enqueue (https://deno.land/std/ws/mod.ts:306:13)
    at WebSocketImpl.send (https://deno.land/std/ws/mod.ts:327:17)
    at Gateway.singleHeartbeat (https://deno.land/x/coward/src/network/gateway/WebsocketHandler.ts:63:13)
    at https://deno.land/x/coward/src/network/gateway/WebsocketHandler.ts:74:11
    at fire ($deno$/web/timers.ts:179:3)
    at handleTimerMacrotask ($deno$/web/timers.ts:44:5)
[coward] error: something went wrong when trying to heartbeat:
ConnectionReset: Socket has already been closed
    at WebSocketImpl.enqueue (https://deno.land/std/ws/mod.ts:306:13)
    at WebSocketImpl.send (https://deno.land/std/ws/mod.ts:327:17)
    at Gateway.singleHeartbeat (https://deno.land/x/coward/src/network/gateway/WebsocketHandler.ts:63:13)
    at https://deno.land/x/coward/src/network/gateway/WebsocketHandler.ts:74:11
    at fire ($deno$/web/timers.ts:179:3)
    at handleTimerMacrotask ($deno$/web/timers.ts:44:5)
error: Uncaught ConnectionReset: Socket has already been closed
          new Deno.errors.ConnectionReset("Socket has already been closed")
          ^
    at https://deno.land/std/ws/mod.ts:387:11
    at Array.forEach (<anonymous>)
    at WebSocketImpl.ensureSocketClosed (https://deno.land/std/ws/mod.ts:385:12)
    at WebSocketImpl.close (https://deno.land/std/ws/mod.ts:367:12)
```

**Comment by fox-cat** [comment]
okay, ill work on it!
at least this confirms what i thought haha

**Comment by fox-cat** [comment]
commit ebcff2e on the [`dev`](https://github.com/fox-cat/coward/tree/dev) branch attempts to fix this;
testing would be appreciated
(the dev branch also includes an events overhaul... 
instead of `client.on("fooBar", (foo) => {...`, `client.extFooBar(({foo}) => {...` should be used)

**Comment by C0Nd3Mnd** [comment]
Alrighty, I updated my code for the event handling changes and I'm trying it now.

**Comment by C0Nd3Mnd** [comment]
So, after some testing I observed that no error is being thrown now, but instead it just silently disconnects. The bot is shown as offline and the "message created" event does not fire anymore after the silent disconnect.

**Comment by fox-cat** [comment]
hmmm... there's no longer any "something went wrong when trying to heartbeat" or "websocket is already disconnected" error?

**Comment by C0Nd3Mnd** [comment]
No. It seems like the error is caught and handled in some way, but it does not reconnect properly (I didn't look at the updated code yet, so I'm just guessing).

**Comment by jurgenzz** [comment]
Had the same issue. Updated to dev branch, now fails silently, without any errors, just disconnected from discord.

**Comment by fox-cat** [comment]
thanks for letting me know; i will work on it
